[tool.poetry]
name = "poirot"
version = "0.1.0"
description = ""
authors = ["harumonia <zxjlm233@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.8"
fastapi = "^0.95.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
